// This file is auto-generated by @hey-api/openapi-ts

/**
 * GetEvent
 */
export type GetEvent = {
    id: number;
    name: string;
    code: string;
    is_active: boolean;
    whitelist: {
        [key: string]: unknown;
    };
    created_at: string;
    updated_at: string;
};

/**
 * GetQuestion
 */
export type GetQuestion = {
    id: number;
    question: string;
    is_signup_question: boolean;
    is_game_question: boolean;
    created_at: string;
    updated_at: string;
};

/**
 * GetUser
 */
export type GetUser = {
    id: number;
    name: string;
    email: string;
    points: number;
    qr_code: string;
    connection_count: number;
    status: UserStatus;
    is_admin: boolean;
    event_id?: number | null;
    created_at: string;
    updated_at: string;
};

/**
 * GetUserAnswer
 */
export type GetUserAnswer = {
    id: number;
    answer: string;
    user_id: number;
    question_id: number;
    created_at: string;
    updated_at: string;
};

/**
 * PatchEvent
 */
export type PatchEvent = {
    name?: string;
    code?: string;
    is_active?: boolean;
    whitelist?: {
        [key: string]: unknown;
    };
};

/**
 * PatchQuestion
 */
export type PatchQuestion = {
    question?: string;
    is_signup_question?: boolean;
    is_game_question?: boolean;
};

/**
 * PatchUser
 */
export type PatchUser = {
    name?: string;
};

/**
 * PatchUserAnswer
 */
export type PatchUserAnswer = {
    answer?: string;
};

/**
 * PostEvent
 */
export type PostEvent = {
    name: string;
    code: string;
};

/**
 * PostLogin
 */
export type PostLogin = {
    email: string;
    event_code: string;
};

/**
 * PostQuestion
 */
export type PostQuestion = {
    question: string;
    is_signup_question: boolean;
    is_game_question: boolean;
};

/**
 * PostUser
 */
export type PostUser = {
    name: string;
    email: string;
    event_code: string;
};

/**
 * PostUserAnswer
 */
export type PostUserAnswer = {
    answer: string;
    question_id: number;
};

/**
 * UserStatus
 */
export type UserStatus = 'available' | 'connecting' | 'busy';

export type ApiAuthMeGetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type ApiAuthMeGetUserResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: GetUser;
};

export type ApiAuthMeGetUserResponse = ApiAuthMeGetUserResponses[keyof ApiAuthMeGetUserResponses];

export type ApiAuthLoginLoginData = {
    body: PostLogin;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type ApiAuthLoginLoginErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiAuthLoginLoginError = ApiAuthLoginLoginErrors[keyof ApiAuthLoginLoginErrors];

export type ApiAuthLoginLoginResponses = {
    /**
     * Document created, URL follows
     */
    201: {
        [key: string]: unknown;
    };
};

export type ApiAuthLoginLoginResponse = ApiAuthLoginLoginResponses[keyof ApiAuthLoginLoginResponses];

export type ApiEventsEventIdDeleteEventData = {
    body?: never;
    path: {
        event_id: number;
    };
    query?: never;
    url: '/api/events/{event_id}';
};

export type ApiEventsEventIdDeleteEventErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiEventsEventIdDeleteEventError = ApiEventsEventIdDeleteEventErrors[keyof ApiEventsEventIdDeleteEventErrors];

export type ApiEventsEventIdDeleteEventResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: GetEvent;
};

export type ApiEventsEventIdDeleteEventResponse = ApiEventsEventIdDeleteEventResponses[keyof ApiEventsEventIdDeleteEventResponses];

export type ApiEventsEventIdGetEventData = {
    body?: never;
    path: {
        event_id: number;
    };
    query?: never;
    url: '/api/events/{event_id}';
};

export type ApiEventsEventIdGetEventErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiEventsEventIdGetEventError = ApiEventsEventIdGetEventErrors[keyof ApiEventsEventIdGetEventErrors];

export type ApiEventsEventIdGetEventResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: GetEvent;
};

export type ApiEventsEventIdGetEventResponse = ApiEventsEventIdGetEventResponses[keyof ApiEventsEventIdGetEventResponses];

export type ApiEventsEventIdPatchEventData = {
    body: PatchEvent;
    path: {
        event_id: number;
    };
    query?: never;
    url: '/api/events/{event_id}';
};

export type ApiEventsEventIdPatchEventErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiEventsEventIdPatchEventError = ApiEventsEventIdPatchEventErrors[keyof ApiEventsEventIdPatchEventErrors];

export type ApiEventsEventIdPatchEventResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: GetEvent;
};

export type ApiEventsEventIdPatchEventResponse = ApiEventsEventIdPatchEventResponses[keyof ApiEventsEventIdPatchEventResponses];

export type ApiEventsGetEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/events';
};

export type ApiEventsGetEventsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<GetEvent>;
};

export type ApiEventsGetEventsResponse = ApiEventsGetEventsResponses[keyof ApiEventsGetEventsResponses];

export type ApiEventsPostEventData = {
    body: PostEvent;
    path?: never;
    query?: never;
    url: '/api/events';
};

export type ApiEventsPostEventErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiEventsPostEventError = ApiEventsPostEventErrors[keyof ApiEventsPostEventErrors];

export type ApiEventsPostEventResponses = {
    /**
     * Document created, URL follows
     */
    201: GetEvent;
};

export type ApiEventsPostEventResponse = ApiEventsPostEventResponses[keyof ApiEventsPostEventResponses];

export type ApiQuestionsQuestionIdDeleteQuestionData = {
    body?: never;
    path: {
        question_id: number;
    };
    query?: never;
    url: '/api/questions/{question_id}';
};

export type ApiQuestionsQuestionIdDeleteQuestionErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiQuestionsQuestionIdDeleteQuestionError = ApiQuestionsQuestionIdDeleteQuestionErrors[keyof ApiQuestionsQuestionIdDeleteQuestionErrors];

export type ApiQuestionsQuestionIdDeleteQuestionResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: GetQuestion;
};

export type ApiQuestionsQuestionIdDeleteQuestionResponse = ApiQuestionsQuestionIdDeleteQuestionResponses[keyof ApiQuestionsQuestionIdDeleteQuestionResponses];

export type ApiQuestionsQuestionIdGetQuestionData = {
    body?: never;
    path: {
        question_id: number;
    };
    query?: never;
    url: '/api/questions/{question_id}';
};

export type ApiQuestionsQuestionIdGetQuestionErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiQuestionsQuestionIdGetQuestionError = ApiQuestionsQuestionIdGetQuestionErrors[keyof ApiQuestionsQuestionIdGetQuestionErrors];

export type ApiQuestionsQuestionIdGetQuestionResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: GetQuestion;
};

export type ApiQuestionsQuestionIdGetQuestionResponse = ApiQuestionsQuestionIdGetQuestionResponses[keyof ApiQuestionsQuestionIdGetQuestionResponses];

export type ApiQuestionsQuestionIdPatchQuestionData = {
    body: PatchQuestion;
    path: {
        question_id: number;
    };
    query?: never;
    url: '/api/questions/{question_id}';
};

export type ApiQuestionsQuestionIdPatchQuestionErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiQuestionsQuestionIdPatchQuestionError = ApiQuestionsQuestionIdPatchQuestionErrors[keyof ApiQuestionsQuestionIdPatchQuestionErrors];

export type ApiQuestionsQuestionIdPatchQuestionResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: GetQuestion;
};

export type ApiQuestionsQuestionIdPatchQuestionResponse = ApiQuestionsQuestionIdPatchQuestionResponses[keyof ApiQuestionsQuestionIdPatchQuestionResponses];

export type ApiQuestionsGetQuestionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/questions';
};

export type ApiQuestionsGetQuestionsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<GetQuestion>;
};

export type ApiQuestionsGetQuestionsResponse = ApiQuestionsGetQuestionsResponses[keyof ApiQuestionsGetQuestionsResponses];

export type ApiQuestionsPostQuestionData = {
    body: PostQuestion;
    path?: never;
    query?: never;
    url: '/api/questions';
};

export type ApiQuestionsPostQuestionErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiQuestionsPostQuestionError = ApiQuestionsPostQuestionErrors[keyof ApiQuestionsPostQuestionErrors];

export type ApiQuestionsPostQuestionResponses = {
    /**
     * Document created, URL follows
     */
    201: GetQuestion;
};

export type ApiQuestionsPostQuestionResponse = ApiQuestionsPostQuestionResponses[keyof ApiQuestionsPostQuestionResponses];

export type ApiUsersUserIdDeleteUserData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type ApiUsersUserIdDeleteUserErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiUsersUserIdDeleteUserError = ApiUsersUserIdDeleteUserErrors[keyof ApiUsersUserIdDeleteUserErrors];

export type ApiUsersUserIdDeleteUserResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: GetUser;
};

export type ApiUsersUserIdDeleteUserResponse = ApiUsersUserIdDeleteUserResponses[keyof ApiUsersUserIdDeleteUserResponses];

export type ApiUsersUserIdGetUserData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type ApiUsersUserIdGetUserErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiUsersUserIdGetUserError = ApiUsersUserIdGetUserErrors[keyof ApiUsersUserIdGetUserErrors];

export type ApiUsersUserIdGetUserResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: GetUser;
};

export type ApiUsersUserIdGetUserResponse = ApiUsersUserIdGetUserResponses[keyof ApiUsersUserIdGetUserResponses];

export type ApiUsersUserIdPatchUserData = {
    body: PatchUser;
    path: {
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type ApiUsersUserIdPatchUserErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiUsersUserIdPatchUserError = ApiUsersUserIdPatchUserErrors[keyof ApiUsersUserIdPatchUserErrors];

export type ApiUsersUserIdPatchUserResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: GetUser;
};

export type ApiUsersUserIdPatchUserResponse = ApiUsersUserIdPatchUserResponses[keyof ApiUsersUserIdPatchUserResponses];

export type ApiUsersGetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type ApiUsersGetUsersResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<GetUser>;
};

export type ApiUsersGetUsersResponse = ApiUsersGetUsersResponses[keyof ApiUsersGetUsersResponses];

export type ApiUsersPostUserData = {
    body: PostUser;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type ApiUsersPostUserErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiUsersPostUserError = ApiUsersPostUserErrors[keyof ApiUsersPostUserErrors];

export type ApiUsersPostUserResponses = {
    /**
     * Document created, URL follows
     */
    201: GetUser;
};

export type ApiUsersPostUserResponse = ApiUsersPostUserResponses[keyof ApiUsersPostUserResponses];

export type ApiUserAnswersUserAnswerIdDeleteUserAnswerData = {
    body?: never;
    path: {
        user_answer_id: number;
    };
    query?: never;
    url: '/api/user-answers/{user_answer_id}';
};

export type ApiUserAnswersUserAnswerIdDeleteUserAnswerErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiUserAnswersUserAnswerIdDeleteUserAnswerError = ApiUserAnswersUserAnswerIdDeleteUserAnswerErrors[keyof ApiUserAnswersUserAnswerIdDeleteUserAnswerErrors];

export type ApiUserAnswersUserAnswerIdDeleteUserAnswerResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: GetUserAnswer;
};

export type ApiUserAnswersUserAnswerIdDeleteUserAnswerResponse = ApiUserAnswersUserAnswerIdDeleteUserAnswerResponses[keyof ApiUserAnswersUserAnswerIdDeleteUserAnswerResponses];

export type ApiUserAnswersUserAnswerIdGetUserAnswerData = {
    body?: never;
    path: {
        user_answer_id: number;
    };
    query?: never;
    url: '/api/user-answers/{user_answer_id}';
};

export type ApiUserAnswersUserAnswerIdGetUserAnswerErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiUserAnswersUserAnswerIdGetUserAnswerError = ApiUserAnswersUserAnswerIdGetUserAnswerErrors[keyof ApiUserAnswersUserAnswerIdGetUserAnswerErrors];

export type ApiUserAnswersUserAnswerIdGetUserAnswerResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: GetUserAnswer;
};

export type ApiUserAnswersUserAnswerIdGetUserAnswerResponse = ApiUserAnswersUserAnswerIdGetUserAnswerResponses[keyof ApiUserAnswersUserAnswerIdGetUserAnswerResponses];

export type ApiUserAnswersUserAnswerIdPatchUserAnswerData = {
    body: PatchUserAnswer;
    path: {
        user_answer_id: number;
    };
    query?: never;
    url: '/api/user-answers/{user_answer_id}';
};

export type ApiUserAnswersUserAnswerIdPatchUserAnswerErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiUserAnswersUserAnswerIdPatchUserAnswerError = ApiUserAnswersUserAnswerIdPatchUserAnswerErrors[keyof ApiUserAnswersUserAnswerIdPatchUserAnswerErrors];

export type ApiUserAnswersUserAnswerIdPatchUserAnswerResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: GetUserAnswer;
};

export type ApiUserAnswersUserAnswerIdPatchUserAnswerResponse = ApiUserAnswersUserAnswerIdPatchUserAnswerResponses[keyof ApiUserAnswersUserAnswerIdPatchUserAnswerResponses];

export type ApiUserAnswersGetUserAnswersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user-answers';
};

export type ApiUserAnswersGetUserAnswersResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<GetUserAnswer>;
};

export type ApiUserAnswersGetUserAnswersResponse = ApiUserAnswersGetUserAnswersResponses[keyof ApiUserAnswersGetUserAnswersResponses];

export type ApiUserAnswersPostUserAnswerData = {
    body: PostUserAnswer;
    path?: never;
    query?: never;
    url: '/api/user-answers';
};

export type ApiUserAnswersPostUserAnswerErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiUserAnswersPostUserAnswerError = ApiUserAnswersPostUserAnswerErrors[keyof ApiUserAnswersPostUserAnswerErrors];

export type ApiUserAnswersPostUserAnswerResponses = {
    /**
     * Document created, URL follows
     */
    201: GetUserAnswer;
};

export type ApiUserAnswersPostUserAnswerResponse = ApiUserAnswersPostUserAnswerResponses[keyof ApiUserAnswersPostUserAnswerResponses];

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};
